name: Test Action

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm start &
      - run: sleep 3
      - run: npm ci
        working-directory: .github/actions/call-node-api
      - uses: ./.github/actions/call-node-api
        with:
          api-url: http://localhost:3000/status
      - run: cat README.md
